repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: fix-encoding-pragma
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
- repo: local
  hooks:
  - id: flynt
    name: flynt
    entry: flynt
    args: [--fail-on-change]
    types: [python]
    language: python
    additional_dependencies:
       - flynt
