repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: fix-encoding-pragma
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -  id: isort
       name: run isort
       entry: isort
       args: [-yq]
       language: python
       additional_dependencies:
         - isort
         - toml
- repo: local
  hooks:
  - id: flynt
    name: flynt
    entry: flynt
    args: [--fail-on-change]
    types: [python]
    language: python
    additional_dependencies:
       - flynt
#- repo: local
#  hooks:
#  - id: version
#    name: update version from SCM tags
#    entry: poetry-dynamic-versioning
#    always_run: true
#    exclude: .*
#    language: system
- repo: local
  hooks:
  - id: tests
    name: run tests
    entry: pytest -s
    language: system
    types: [python]
    stages: [push]
